import createUserValidationSchema  from '../dtos/create-user.dto.ts
export const createUserValidator = async (
  req: Request,
  res: Response,
  next: NextFunction
) => {
  try {
    if (!req.body) {
      return res.status(400).send({ message: 'Missing request body!' });
    }

    // the validateAsync method is built into Joi
    await createUserValidationSchema.validateAsync(req.body);

    next();
  } catch (e: any) {
    // if validation fails we send the message generated by Joi
    res.status(400).send({ message: e.message });
  }
};
